// Generated by https://quicktype.io

export interface Quotes {
  quotes: Quote[];
  links: Link[];
}

export interface Link {
  rel: string;
  href: string;
}

export interface Quote {
  listingKey: string;
  fields: Fields;
  links: Link[];
}

export interface Fields {
  [key: string]: DataFields;
}

export interface DataFields {
  d: string;
  dly: number;
  gen: number;
  v: number;
  z?: number;
}
